runtime:
  cache_dir: ./.cache/antora
site:
  title: The Docs @ OpenNMS
  url: https://docs.opennms.eu
  start_page: horizon::index.adoc
content:
  sources:
  - url: &opennms-doc-url https://github.com/no42-org/opennms.git
    branches: &opennms-doc-branches master
    start_path: opennms-doc/releasenotes
  - url: *opennms-doc-url
    branches: *opennms-doc-branches
    start_path: opennms-doc/guide-install
asciidoc:
  attributes:
    experimental: ''
    example-caption: ~
    hide-uri-scheme: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    source-language: asciidoc
    table-caption: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
#  supplemental_files: ./supplemental-ui
output:
  dir: ./public
