#runtime:
#  cache_dir: ./.cache/antora
site:
  title: The Docs @ OpenNMS
  url: https://docs.opennms.eu
content:
  sources:
  - url: &docs-url https://github.com/no42-org/opennms.git
    branches: &horizon-docs-branches master
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    example-caption: ~
    hide-uri-scheme: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    source-language: asciidoc
    table-caption: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
#  supplemental_files: ./supplemental-ui
output:
  dir: ./public
